#region Copyright
///////////////////////////////////////////////////////////////////////////////
//
//  Copyright (c) Phoenix Contact GmbH & Co KG
//  This software is licensed under Apache-2.0
//
///////////////////////////////////////////////////////////////////////////////
#endregion

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlcNextVSExtension.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlcNextVSExtension.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to generate code.
        /// </summary>
        internal static string Command_generate_code {
            get {
                return ResourceManager.GetString("Command_generate_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get compiler-specifications.
        /// </summary>
        internal static string Command_get_compiler_specifications {
            get {
                return ResourceManager.GetString("Command_get_compiler-specifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get project-information.
        /// </summary>
        internal static string Command_get_project_information {
            get {
                return ResourceManager.GetString("Command_get_project-information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get targets.
        /// </summary>
        internal static string Command_get_targets {
            get {
                return ResourceManager.GetString("Command_get_targets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new acfcomponent.
        /// </summary>
        internal static string Command_new_acfcomponent {
            get {
                return ResourceManager.GetString("Command_new_acfcomponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new acfproject.
        /// </summary>
        internal static string Command_new_acfproject {
            get {
                return ResourceManager.GetString("Command_new_acfproject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new component.
        /// </summary>
        internal static string Command_new_component {
            get {
                return ResourceManager.GetString("Command_new_component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new consumablelibrary.
        /// </summary>
        internal static string Command_new_consumablelibrary {
            get {
                return ResourceManager.GetString("Command_new_consumablelibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new project.
        /// </summary>
        internal static string Command_new_plmproject {
            get {
                return ResourceManager.GetString("Command_new_plmproject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new program.
        /// </summary>
        internal static string Command_new_program {
            get {
                return ResourceManager.GetString("Command_new_program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set target.
        /// </summary>
        internal static string Command_set_target {
            get {
                return ResourceManager.GetString("Command_set_target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to component.
        /// </summary>
        internal static string ItemType_component {
            get {
                return ResourceManager.GetString("ItemType_component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to program.
        /// </summary>
        internal static string ItemType_program {
            get {
                return ResourceManager.GetString("ItemType_program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -p.
        /// </summary>
        internal static string Option_generate_code_project {
            get {
                return ResourceManager.GetString("Option_generate_code_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -p.
        /// </summary>
        internal static string Option_get_compiler_specifications_project {
            get {
                return ResourceManager.GetString("Option_get_compiler-specifications_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -n.
        /// </summary>
        internal static string Option_get_project_information_no_include_detection {
            get {
                return ResourceManager.GetString("Option_get_project_information_no_include_detection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -p.
        /// </summary>
        internal static string Option_get_project_information_project {
            get {
                return ResourceManager.GetString("Option_get_project-information_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -n.
        /// </summary>
        internal static string Option_new_component_name {
            get {
                return ResourceManager.GetString("Option_new_component_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -s.
        /// </summary>
        internal static string Option_new_component_namespace {
            get {
                return ResourceManager.GetString("Option_new_component_namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -p.
        /// </summary>
        internal static string Option_new_component_project {
            get {
                return ResourceManager.GetString("Option_new_component_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -c.
        /// </summary>
        internal static string Option_new_program_component {
            get {
                return ResourceManager.GetString("Option_new_program_component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -n.
        /// </summary>
        internal static string Option_new_program_name {
            get {
                return ResourceManager.GetString("Option_new_program_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -s.
        /// </summary>
        internal static string Option_new_program_namespace {
            get {
                return ResourceManager.GetString("Option_new_program_namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -p.
        /// </summary>
        internal static string Option_new_program_project {
            get {
                return ResourceManager.GetString("Option_new_program_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -c.
        /// </summary>
        internal static string Option_new_project_componentName {
            get {
                return ResourceManager.GetString("Option_new_project_componentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -o.
        /// </summary>
        internal static string Option_new_project_output {
            get {
                return ResourceManager.GetString("Option_new_project_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -p.
        /// </summary>
        internal static string Option_new_project_programName {
            get {
                return ResourceManager.GetString("Option_new_project_programName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -n.
        /// </summary>
        internal static string Option_new_project_projectNamespace {
            get {
                return ResourceManager.GetString("Option_new_project_projectNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -a.
        /// </summary>
        internal static string Option_set_target_add {
            get {
                return ResourceManager.GetString("Option_set_target_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -n.
        /// </summary>
        internal static string Option_set_target_name {
            get {
                return ResourceManager.GetString("Option_set_target_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -p.
        /// </summary>
        internal static string Option_set_target_project {
            get {
                return ResourceManager.GetString("Option_set_target_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -r.
        /// </summary>
        internal static string Option_set_target_remove {
            get {
                return ResourceManager.GetString("Option_set_target_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -v.
        /// </summary>
        internal static string Option_set_target_version {
            get {
                return ResourceManager.GetString("Option_set_target_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acfproject.
        /// </summary>
        internal static string ProjectType_ACF {
            get {
                return ResourceManager.GetString("ProjectType_ACF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to consumablelibrary.
        /// </summary>
        internal static string ProjectType_ConsumableLibrary {
            get {
                return ResourceManager.GetString("ProjectType_ConsumableLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to project.
        /// </summary>
        internal static string ProjectType_PLM {
            get {
                return ResourceManager.GetString("ProjectType_PLM", resourceCulture);
            }
        }
    }
}
